name: Push rapidocr_table_torch to pypi

on:
  push:
    tags:
      - torch_v*

env:
  RESOURCES_URL: https://github.com/RapidAI/RapidTable/releases/download/assets/unitable.zip


jobs:
  UnitTesting:
    runs-on: ubuntu-latest
    steps:
      - name: Pull latest code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Unit testings
        run: |
          pip install -r requirements_torch.txt
          pip install rapidocr_onnxruntime
          pip install pytest
          pytest tests/test_table_torch.py

  GenerateWHL_PushPyPi:
    needs: UnitTesting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'

      - name: Run setup_torch.py
        run: |
          pip install -r requirements_torch.txt
          python -m pip install --upgrade pip
          pip install wheel get_pypi_latest_version
          python setup.py bdist_wheel ${{ github.ref_name }}

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          password: ${{ secrets.RAPID_TABLE }}
          packages_dir: dist/
